### ISSUE TITLE
CUDA device-side assert (srcIndex < srcSelectDimSize) on custom PDB, while example works fine

### ISSUE THREAD

**Issue by Gu-SeongHoe** [kxz18/PepMimic#6]
Hi, thank you for this excellent repository. I've run into a persistent CUDA error when running mimic_design.py that I haven't been able to solve.

**The provided example data(CD38) runs perfectly**
However, when I use other PDB file (6R7T.pdb from RCSB), the script fails immediately at the 0% sampling step with RuntimeError: CUDA error: device-side assert triggered (specifically, Assertion 'srcIndex < srcSelectDimSize' failed).

The config.yaml setting is
dataset:
  test:
    class: MimicryDataset
    ref_dir: ./example_data/MAGEB1 
    n_sample_per_cplx: 50        
    length_lb: 15                 
    length_ub: 50                 

dataloader:
  num_workers: 4
  batch_size: 32

and index.txt is
6R7T	B	A	-

Are there any specific formatting requirements for the PDB files? Or is a preprocessing step necessary for PDB files from RCSB?

Thank you for your help.

**Comment by kxz18** [comment]
Hi, the index file seems ok. Would you mind providing the detailed error traceback given by the program?

**Comment by Gu-SeongHoe** [comment]
Hi, thank you for looking into this. Here is the detailed traceback:

The error starts with a long series of CUDA assertion failures:

  0%|          | 0/2 [00:00<?, ?it/s]/opt/conda/conda-bld/pytorch_1729647382455/work/aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [119,0,0], thread: [64,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1729647382455/work/aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [119,0,0], thread: [65,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1729647382455/work/aten/src/ATen/native/cuda/Indexing.cu:1308: indexSelectLargeIndex: block: [119,0,0], thread: [66,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
... (many similar "Assertion `srcIndex < srcSelectDimSize` failed" lines) ...

This eventually leads to the following Python Traceback:

Traceback (most recent call last):
  File "[.../path/to/PepMimic]/mimic_design.py", line 250, in <module>
    main(args, opt_args)
  File "[.../path/to/PepMimic]/mimic_design.py", line 196, in main
    batch_X, batch_S, batch_pmetric = model.sample(
  File "[.../python/site-packages]/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "[.../path/to/PepMimic]/models/ifencoder/model.py", line 279, in sample
    sample_X, sample_S, sample_ppl = self.ldm.sample(X, S, mask, position_ids, lengths, atom_mask, L, sample_opt, return_tensor, optimize_sidechain, idealize)
  File "[.../python/site-packages]/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "[.../path/to/PepMimic]/models/LDM/ldm.py", line 200, in sample
    atom_mask_gen = atom_mask[mask]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1

**Comment by kxz18** [comment]
TL;DR: length_ub in the configuration should be set to <= 25.

Hi, I guess it might be because the upperbound of the peptide length is too large in the configuration (length_ub: 50). The model was trained on a dataset with peptide length below 25, so the index error might be due to the out-of-range problem for position encodings. And it might also cause some unknown trouble when setting the length above 25 during inference, since it is out-of-distribution for the generative model. I tried your case with length_ub setting to 25 and it worked.

**Comment by Gu-SeongHoe** [comment]
Hi, thank you so much for your help!

You were exactly right. I changed length_ub to 25 in my config.yaml, and it works perfectly now.

I really appreciate you taking the time to point me in the right direction after I was so focused on the PDB file format.

Thanks again for solving this! I'll close the issue.

**Comment by kxz18** [comment]
You are welcome! It's really helpful because this issue reminds of putting the length limitations in the README.
